name: Periodic run
on:
  push
  # schedule:
  #   # Every 10 min
  #   - cron: "*/10 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          npx playwright install-deps

      - name: Setup
        run: |
          yarn install
          npx playwright install

      - name: Refresh
        run: yarn refresh
