name: Periodic run
on:
  schedule:
    # Every 30 min
    - cron: "*/30 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        run: |
          yarn install
          npx playwright install

      - name: Set up env
        run: |
          touch .env
          echo USERNAME=${{ secrets.USERNAME }} >> .env
          echo PASSWORD=${{ secrets.PASSWORD }} >> .env
          echo URL=${{ secrets.URL }} >> .env

      - name: Refresh
        run: yarn refresh
