name: Periodic run
on:
  schedule:
    # Every 20 min. Need to fit within the 2,000 min/mo GH limit.
    - cron: "*/20 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - name: Setup
        run: |
          yarn install
          npx playwright install chromium

      - name: Set up env
        run: |
          touch .env
          echo USERNAME=${{ secrets.USERNAME }} >> .env
          echo PASSWORD=${{ secrets.PASSWORD }} >> .env
          echo URL=${{ secrets.URL }} >> .env

      - name: Refresh
        run: yarn refresh
